#Pandas Learning

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

In [49]:
data_frame = pd.read_csv('chipotle.tsv',sep='\t')

In [4]:
data_frame.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [8]:
data_frame.shape

(4622, 5)

In [9]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [10]:
data_frame.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [11]:
data_frame.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

# Loc vs iloc

In [23]:
data_frame.loc[(data_frame.quantity == 15) | (data_frame.quantity == 5), ['order_id', 'quantity']]  # Lọc các giá trị

      order_id  quantity
2441       970         5
3598      1443        15

In [29]:
data_frame.iloc[[3,5]]  # Lấy dòng thứ 4 (vì chỉ số bắt đầu từ 0) và dòng thứ 6 (vì chỉ số bắt đầu từ 0) và tất cả các cột

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98

In [42]:
x = data_frame.iloc[4:9]
x

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25

In [38]:
x['quantity'] = x['quantity'].astype(float)
x

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_17972\4022504780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['quantity'] = x['quantity'].astype(float)

,order_id,quantity,item_name,choice_description,item_price
4,2,2.0,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1.0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1.0,Side of Chips,NaN,$1.69
7,4,1.0,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1.0,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25

In [43]:
data_frame.item_price.dtype

dtype('O')

In [45]:
data_frame.item_price.apply(lambda x: float(x.replace('$', '')))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [50]:
data_frame.item_price = data_frame.item_price.apply(lambda x: float(x.replace('$', '')))

In [51]:
data_frame.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [56]:
data_frame['total_price'] = data_frame.quantity * data_frame.item_price
data_frame.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [59]:
print(f'Tổng doanh thu: {data_frame.total_price.sum()}')

Tổng doanh thu: 39237.02

In [67]:
data_frame.order_id.value_counts().sort_values(ascending=True)

order_id
2        1
1813     1
72       1
66       1
60       1
        ..
1786    11
759     11
205     12
1483    14
926     23
Name: count, Length: 1834, dtype: int64